#!/usr/bin/env python3
"""Generate FAIcons.swift from the Font Awesome desktop metadata.

Reads Grocer/Shared/FontAwesome/icon-families.json (the Pro "Jelly" families
metadata) and the Jelly Duo OTF cmap, then emits a compact Swift lookup table
mapping every Font Awesome icon name (and its aliases) to its unicode scalar,
plus the set of icons that carry a duotone secondary layer.

Run from apps/ios:
    python3 Scripts/generate_fa_icons.py

Requires: fonttools  (pip3 install fonttools)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
IOS = os.path.dirname(HERE)
FA = os.path.join(IOS, "Grocer", "Shared", "FontAwesome")
META = os.path.join(HERE, "fa-metadata", "icon-families.json")
DUO_OTF = os.path.join(FA, "Fonts", "FontAwesome7JellyDuo-Regular.otf")
OUT = os.path.join(FA, "FAIcons.swift")

SECONDARY_OFFSET = 0x100000


def duo_secondary_scalars():
    from fontTools.ttLib import TTFont
    cmap = TTFont(DUO_OTF).getBestCmap()
    return {cp - SECONDARY_OFFSET for cp in cmap if cp >= SECONDARY_OFFSET}


def main():
    meta = json.load(open(META))
    has_secondary = duo_secondary_scalars()

    # name -> scalar (canonical names win; aliases fill in without clobbering)
    entries = {}
    duo = set()
    for name, e in sorted(meta.items()):
        scalar = int(e["unicode"], 16)
        entries[name] = scalar
        if scalar in has_secondary:
            duo.add(scalar)
        for alias in e.get("aliases", {}).get("names", []):
            entries.setdefault(alias, scalar)

    # The glyph map is emitted as a compact "name=hex" newline string decoded at
    # runtime — a ~3.8k-entry Swift dictionary *literal* type-checks very slowly,
    # while a single string literal compiles instantly.
    packed = "\n".join(f"{name}={entries[name]:x}" for name in sorted(entries))

    lines = []
    lines.append("// Generated by Scripts/generate_fa_icons.py — do not edit by hand.")
    lines.append("// Source: Font Awesome 7 desktop metadata (Jelly families + Classic Solid).")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    lines.append("enum FAIcons {")
    lines.append("    /// Font Awesome icon name (including aliases) -> primary unicode scalar.")
    lines.append("    static let glyphs: [String: UInt32] = decode(packed)")
    lines.append("")
    lines.append("    /// Primary scalars that carry a Jelly Duo secondary (duotone) layer.")
    lines.append("    static let duotoneScalars: Set<UInt32> = [")
    for s in sorted(duo):
        lines.append(f"        0x{s:04x},")
    lines.append("    ]")
    lines.append("")
    lines.append("    private static func decode(_ s: String) -> [String: UInt32] {")
    lines.append("        var map = [String: UInt32]()")
    lines.append("        map.reserveCapacity(4096)")
    lines.append("        for line in s.split(separator: \"\\n\") {")
    lines.append("            guard let eq = line.firstIndex(of: \"=\"),")
    lines.append("                  let value = UInt32(line[line.index(after: eq)...], radix: 16)")
    lines.append("            else { continue }")
    lines.append("            map[String(line[..<eq])] = value")
    lines.append("        }")
    lines.append("        return map")
    lines.append("    }")
    lines.append("")
    lines.append('    private static let packed = """')
    lines.append(packed)
    lines.append('"""')
    lines.append("}")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT}: {len(entries)} names, {len(duo)} duotone icons")


if __name__ == "__main__":
    main()
