/**
 * Cross-isolate single-flight for product-image generation.
 *
 * Cloudflare Workers run in many isolates, so the per-isolate in-flight map in
 * productImage.ts can't stop two *different* isolates from cold-generating the
 * SAME brand-new item at the same moment — exactly the burst we saw in
 * production (e.g. "lox" generated 5× within 3 seconds, before the first
 * generation finished persisting to R2). These helpers use an atomic R2
 * "create-if-absent" write (`If-None-Match: *`) as a distributed lock so only
 * one isolate calls OpenAI; the others poll R2 for the finished image and pay
 * nothing.
 *
 * The winner persists the image to R2 *before* releasing the lock, so by the
 * time the lock disappears the image is already a cache hit for everyone else.
 */

const LOCK_PREFIX = "product-images/locks/";

/**
 * A generation lock older than this is treated as abandoned (its holder crashed
 * or was evicted mid-generation) and may be stolen. Comfortably longer than a
 * normal cold generation (~10s) so we don't steal a lock that's still working.
 */
export const LOCK_TTL_MS = 30_000;

export function lockKey(canonical: string): string {
  return `${LOCK_PREFIX}${canonical}.lock`;
}

/**
 * Attempts to claim the exclusive right to generate `canonical` across all
 * isolates. Returns true if we won (and must generate), false if another isolate
 * is already generating. A lock older than {@link LOCK_TTL_MS} is stolen so a
 * crashed generation can't wedge an item forever.
 */
export async function acquireGenerationLock(
  images: R2Bucket,
  canonical: string,
): Promise<boolean> {
  const key = lockKey(canonical);
  try {
    // `If-None-Match: *` => store only if no object exists. Returns null when the
    // lock is already held, giving us an atomic compare-and-set across isolates.
    const created = await images.put(key, "1", {
      onlyIf: new Headers({ "If-None-Match": "*" }),
      httpMetadata: { cacheControl: "no-store" },
    });
    if (created) return true;
  } catch (err) {
    // If conditional writes ever error, don't wedge generation — let the caller
    // proceed. Worst case is a rare duplicate, i.e. the pre-lock behavior.
    console.warn("[imageLock] acquire failed, proceeding without lock:", err);
    return true;
  }

  // Lock is held — steal it only if the holder looks dead.
  try {
    const head = await images.head(key);
    if (!head || Date.now() - head.uploaded.getTime() > LOCK_TTL_MS) {
      await images.put(key, "1", { httpMetadata: { cacheControl: "no-store" } });
      return true;
    }
  } catch {
    // Treat as still held; the waiter path will poll for the image.
  }
  return false;
}

export async function releaseGenerationLock(
  images: R2Bucket,
  canonical: string,
): Promise<void> {
  try {
    await images.delete(lockKey(canonical));
  } catch {
    // Best-effort: a leftover lock self-heals via the TTL steal above.
  }
}

export interface AwaitImageOptions {
  pollIntervalMs?: number;
  timeoutMs?: number;
  /** Injectable for tests so the poll loop doesn't sleep on real timers. */
  sleep?: (ms: number) => Promise<void>;
}

const defaultSleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

/**
 * Polls R2 for an image currently being generated by the lock holder in another
 * isolate. Resolves with the bytes once they land, or null if the holder
 * released the lock without producing one (its generation failed) or we time
 * out. Crucially, this path never calls OpenAI, so duplicate concurrent requests
 * cost nothing.
 */
export async function awaitGeneratedImage(
  images: R2Bucket,
  canonical: string,
  exactKey: string,
  options: AwaitImageOptions = {},
): Promise<Uint8Array | null> {
  const pollIntervalMs = options.pollIntervalMs ?? 400;
  const timeoutMs = options.timeoutMs ?? 25_000;
  const sleep = options.sleep ?? defaultSleep;

  for (let waited = 0; waited < timeoutMs; waited += pollIntervalMs) {
    await sleep(pollIntervalMs);

    const hit = await images.get(exactKey);
    if (hit) return new Uint8Array(await hit.arrayBuffer());

    // If the lock is gone but no image exists, the holder failed. Re-check once
    // (the image may have landed between our two reads) then give up.
    const lock = await images.head(lockKey(canonical));
    if (!lock) {
      const late = await images.get(exactKey);
      return late ? new Uint8Array(await late.arrayBuffer()) : null;
    }
  }
  return null;
}
